<?php
define('REMOTE','localhost');
define('DB_NAME','STK');
define('DB_USER','root');
define('DB_PASS','');
define('CONNEX_STRING','mysql:host='.REMOTE.';dbname='.DB_NAME);
define('NPP',3);
define('LimitCotisation',5);
?>